/**
 * Global Header - OtasukeAI
 * 全ページ共通のヘッダーを動的に挿入する
 * 使い方: <script src="/reference/js/global-header.js"></script> を <body> 直後に配置
 *
 * NOTE: inline style で構造レイアウトを固定し、外部 CSS の干渉を完全遮断する
 */
(function () {
  'use strict';

  var HEADER_HTML = ''
    + '<header class="site-header" style="position:fixed;top:0;left:0;width:100%;z-index:9999;background:#fff;box-shadow:0 2px 10px rgba(0,102,204,.08);font-family:\'Noto Sans JP\',sans-serif;font-size:14px;line-height:1.5;letter-spacing:normal;color:#2F363D;margin:0;padding:0;border:none;float:none;transform:none;overflow:visible;box-sizing:border-box;">'
    + '  <div class="header-topbar" style="background:#003366;color:#fff;font-size:12px;padding:6px 0;margin:0;border:none;width:100%;box-sizing:border-box;">'
    + '    <div class="container" style="display:flex;justify-content:space-between;align-items:center;width:100%;max-width:1200px;margin:0 auto;padding:0 20px;height:auto;box-sizing:border-box;">'
    + '      <div class="topbar-left" style="display:flex;align-items:center;gap:20px;">'
    + '        <a href="#" class="topbar-link" style="color:#fff;text-decoration:none;opacity:1;">パートナー・代理店募集</a>'
    + '        <div class="topbar-dropdown" style="position:relative;">'
    + '          <button class="topbar-dropdown-btn" aria-expanded="false" style="background:none;border:none;color:#fff;font-size:12px;cursor:pointer;display:flex;align-items:center;gap:4px;padding:0;font-family:inherit;line-height:inherit;">'
    + '            サービス一覧'
    + '            <svg class="dropdown-arrow" width="10" height="6" viewBox="0 0 10 6" fill="none">'
    + '              <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />'
    + '            </svg>'
    + '          </button>'
    + '          <div class="topbar-dropdown-menu">'
    + '            <a href="#">OTASUKE AI</a>'
    + '            <a href="#">OTASUKE AI DX</a>'
    + '          </div>'
    + '        </div>'
    + '      </div>'
    + '      <div class="topbar-right" style="display:flex;align-items:center;gap:20px;">'
    + '        <a href="#" class="topbar-link" style="color:#fff;text-decoration:none;opacity:1;">AIスタッフ登録</a>'
    + '        <a href="tel:0800080712" class="topbar-tel" style="color:#fff;text-decoration:none;display:flex;align-items:center;gap:6px;font-weight:600;font-size:14px;opacity:1;">'
    + '          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" style="flex-shrink:0;">'
    + '            <path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '          </svg>'
    + '          0800-080-0712<span class="tel-time" style="font-weight:400;font-size:11px;opacity:0.9;">(平日 10:00-18:00)</span>'
    + '        </a>'
    + '      </div>'
    + '    </div>'
    + '  </div>'
    + '  <div class="header-main" style="padding:12px 0;border-bottom:3px solid #4EAEFF;background:#fff;margin:0;width:100%;box-sizing:border-box;">'
    + '    <div class="container" style="display:flex;justify-content:space-between;align-items:center;width:100%;max-width:1320px;margin:0 auto;padding:0 20px;height:auto;box-sizing:border-box;">'
    + '      <a href="/" class="logo" style="text-decoration:none;display:inline-flex;align-items:center;flex-shrink:0;opacity:1;">'
    + '        <span class="logo-text" style="font-family:\'DM Sans\',\'Noto Sans JP\',sans-serif;font-size:28px;font-weight:700;letter-spacing:0.02em;color:#003366;text-decoration:none;line-height:1.2;white-space:nowrap;">OTASUKE<span class="logo-ai" style="color:#0066CC;font-weight:800;">AI</span></span>'
    + '      </a>'
    + '      <button class="hamburger" id="hamburger" aria-label="メニューを開く" aria-expanded="false" style="display:none;background:none;border:none;cursor:pointer;padding:0;font-family:inherit;">'
    + '        <span></span><span></span><span></span>'
    + '      </button>'
    + '      <nav id="nav-menu" class="main-nav" role="navigation" aria-label="メインナビゲーション" style="display:flex;align-items:center;gap:20px;">'
    + '        <div class="mobile-menu-header" style="display:none;">'
    + '          <a href="/" class="mobile-menu-logo">OTASUKE<span class="logo-ai">AI</span></a>'
    + '          <button id="mobile-menu-close" class="mobile-menu-close" aria-label="メニューを閉じる">&times;</button>'
    + '        </div>'
    + '        <a href="tel:0800080712" class="mobile-menu-tel" style="display:none;">'
    + '          <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '            <path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '          </svg>'
    + '          0800-080-0712'
    + '        </a>'
    + '        <ul class="nav-list" style="display:flex;align-items:center;gap:18px;list-style:none;margin:0;padding:0;">'
    + '          <li style="position:relative;list-style-type:none;margin:0;padding:0;"><a href="/" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;display:flex;align-items:center;padding:8px 0;line-height:1.5;opacity:1;">HOME</a></li>'
    + '          <li style="position:relative;list-style-type:none;margin:0;padding:0;"><a href="/reference/merrybiz/service/" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;display:flex;align-items:center;padding:8px 0;line-height:1.5;opacity:1;">サービス</a></li>'
    + '          <li style="position:relative;list-style-type:none;margin:0;padding:0;"><a href="/reference/merrybiz/merit/" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;display:flex;align-items:center;padding:8px 0;line-height:1.5;opacity:1;">解決すること</a></li>'
    + '          <li style="position:relative;list-style-type:none;margin:0;padding:0;"><a href="/reference/hrmos-price/" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;display:flex;align-items:center;padding:8px 0;line-height:1.5;opacity:1;">料金</a></li>'
    + '          <li class="has-dropdown" style="position:relative;list-style-type:none;margin:0;padding:0;">'
    + '            <button class="nav-dropdown-btn" aria-expanded="false" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;background:none;border:none;cursor:pointer;display:flex;align-items:center;gap:4px;padding:8px 0;line-height:1.5;font-family:inherit;">'
    + '              事例'
    + '              <svg class="dropdown-arrow" width="10" height="6" viewBox="0 0 10 6" fill="none">'
    + '                <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </button>'
    + '            <div class="nav-dropdown-menu">'
    + '              <a href="/#voice">導入事例</a>'
    + '              <a href="/#sec06">ご利用までの流れ</a>'
    + '            </div>'
    + '          </li>'
    + '          <li style="position:relative;list-style-type:none;margin:0;padding:0;"><a href="/#sec10" style="color:#2F363D;text-decoration:none;font-weight:500;font-size:14px;display:flex;align-items:center;padding:8px 0;line-height:1.5;opacity:1;">よくある質問</a></li>'
    + '        </ul>'
    + '        <div class="nav-cta-buttons" style="display:flex;gap:8px;">'
    + '          <a href="/payment/" class="nav-cta nav-cta-apply" style="display:flex;align-items:center;gap:5px;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:12px;font-weight:700;white-space:nowrap;line-height:1.4;background:#FFD700;color:#003366;border:2px solid #FFD700;opacity:1;">'
    + '            <span class="cta-icon" style="display:flex;align-items:center;">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M9 12l2 2 4-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            お申し込み'
    + '          </a>'
    + '          <a href="/contact/" class="nav-cta nav-cta-document" style="display:flex;align-items:center;gap:5px;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:12px;font-weight:600;white-space:nowrap;line-height:1.4;background:#fff;color:#0066CC;border:2px solid #0066CC;opacity:1;">'
    + '            <span class="cta-icon" style="display:flex;align-items:center;">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <polyline points="14,2 14,8 20,8" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="16" y1="13" x2="8" y2="13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="16" y1="17" x2="8" y2="17" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            資料請求'
    + '          </a>'
    + '          <a href="/contact/" class="nav-cta nav-cta-contact" style="display:flex;align-items:center;gap:5px;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:12px;font-weight:600;white-space:nowrap;line-height:1.4;background:linear-gradient(135deg,#FF6B35 0%,#FF8C42 100%);color:#fff;border:2px solid transparent;opacity:1;">'
    + '            <span class="cta-icon" style="display:flex;align-items:center;">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            お問い合わせ'
    + '          </a>'
    + '          <a href="/customer-dashboard/" class="nav-cta nav-cta-login" style="display:flex;align-items:center;gap:5px;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:12px;font-weight:600;white-space:nowrap;line-height:1.4;background:linear-gradient(135deg,#003366 0%,#0066cc 100%);color:#fff;border:2px solid transparent;opacity:1;">'
    + '            <span class="cta-icon" style="display:flex;align-items:center;">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <polyline points="10,17 15,12 10,7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="15" y1="12" x2="3" y2="12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            ログインはこちら'
    + '          </a>'
    + '        </div>'
    + '      </nav>'
    + '    </div>'
    + '  </div>'
    + '</header>'
    + '<div class="nav-overlay" id="nav-overlay"></div>';

  // 既存のヘッダーを置換、または body 先頭に挿入
  var existing = document.querySelector('header.site-header');
  if (existing) {
    // nav-overlay も一緒に削除
    var existingOverlay = document.getElementById('nav-overlay');
    if (existingOverlay) existingOverlay.remove();
    existing.insertAdjacentHTML('afterend', HEADER_HTML);
    existing.remove();
  } else {
    document.body.insertAdjacentHTML('afterbegin', HEADER_HTML);
  }
})();
