/**
 * Global Header - OtasukeAI
 * 全ページ共通のヘッダーを動的に挿入する
 * 使い方: <script src="/reference/js/global-header.js"></script> を <body> 直後に配置
 */
(function () {
  'use strict';

  var HEADER_HTML = ''
    + '<header class="site-header">'
    + '  <div class="header-topbar">'
    + '    <div class="container">'
    + '      <div class="topbar-left">'
    + '        <a href="#" class="topbar-link">パートナー・代理店募集</a>'
    + '        <div class="topbar-dropdown">'
    + '          <button class="topbar-dropdown-btn" aria-expanded="false">'
    + '            サービス一覧'
    + '            <svg class="dropdown-arrow" width="10" height="6" viewBox="0 0 10 6" fill="none">'
    + '              <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />'
    + '            </svg>'
    + '          </button>'
    + '          <div class="topbar-dropdown-menu">'
    + '            <a href="#">OTASUKE AI</a>'
    + '            <a href="#">OTASUKE AI DX</a>'
    + '          </div>'
    + '        </div>'
    + '      </div>'
    + '      <div class="topbar-right">'
    + '        <a href="#" class="topbar-link">AIスタッフ登録</a>'
    + '        <a href="tel:0800080712" class="topbar-tel">'
    + '          <svg width="14" height="14" viewBox="0 0 24 24" fill="none">'
    + '            <path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '          </svg>'
    + '          0800-080-0712<span class="tel-time">(平日10:00-18:00)</span>'
    + '        </a>'
    + '      </div>'
    + '    </div>'
    + '  </div>'
    + '  <div class="header-main">'
    + '    <div class="container">'
    + '      <a href="/" class="logo">'
    + '        <span class="logo-text">OTASUKE<span class="logo-ai">AI</span></span>'
    + '      </a>'
    + '      <button class="hamburger" id="hamburger" aria-label="メニューを開く" aria-expanded="false">'
    + '        <span></span><span></span><span></span>'
    + '      </button>'
    + '      <nav id="nav-menu" class="main-nav" role="navigation" aria-label="メインナビゲーション">'
    + '        <ul class="nav-list">'
    + '          <li><a href="/">HOME</a></li>'
    + '          <li><a href="/reference/merrybiz/service/">サービス</a></li>'
    + '          <li><a href="/reference/merrybiz/merit/">解決すること</a></li>'
    + '          <li><a href="/reference/hrmos-price/">料金</a></li>'
    + '          <li class="has-dropdown">'
    + '            <button class="nav-dropdown-btn" aria-expanded="false">'
    + '              事例'
    + '              <svg class="dropdown-arrow" width="10" height="6" viewBox="0 0 10 6" fill="none">'
    + '                <path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </button>'
    + '            <div class="nav-dropdown-menu">'
    + '              <a href="/#voice">導入事例</a>'
    + '              <a href="/#sec06">ご利用までの流れ</a>'
    + '            </div>'
    + '          </li>'
    + '          <li><a href="/#sec10">よくある質問</a></li>'
    + '        </ul>'
    + '        <div class="nav-cta-buttons">'
    + '          <a href="/payment/" class="nav-cta nav-cta-apply">'
    + '            <span class="cta-icon">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M9 12l2 2 4-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            お申し込み'
    + '          </a>'
    + '          <a href="/contact/" class="nav-cta nav-cta-document">'
    + '            <span class="cta-icon">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <polyline points="14,2 14,8 20,8" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="16" y1="13" x2="8" y2="13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="16" y1="17" x2="8" y2="17" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            資料請求'
    + '          </a>'
    + '          <a href="/contact/" class="nav-cta nav-cta-contact">'
    + '            <span class="cta-icon">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            お問い合わせ'
    + '          </a>'
    + '          <a href="/customer-dashboard/" class="nav-cta nav-cta-login">'
    + '            <span class="cta-icon">'
    + '              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">'
    + '                <path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <polyline points="10,17 15,12 10,7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '                <line x1="15" y1="12" x2="3" y2="12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />'
    + '              </svg>'
    + '            </span>'
    + '            ログインはこちら'
    + '          </a>'
    + '        </div>'
    + '      </nav>'
    + '    </div>'
    + '  </div>'
    + '</header>'
    + '<div class="nav-overlay" id="nav-overlay"></div>';

  // 既存のヘッダーを置換、または body 先頭に挿入
  var existing = document.querySelector('header.site-header');
  if (existing) {
    // nav-overlay も一緒に削除
    var existingOverlay = document.getElementById('nav-overlay');
    if (existingOverlay) existingOverlay.remove();
    existing.insertAdjacentHTML('afterend', HEADER_HTML);
    existing.remove();
  } else {
    document.body.insertAdjacentHTML('afterbegin', HEADER_HTML);
  }
})();
